# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV.fetch("DATABASE_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "postgres") %>
  database: <%= ENV.fetch("DATABASE_NAME", "momtools_hub") %>

test:
  <<: *default
  host: <%= ENV.fetch("DATABASE_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "postgres") %>
  database: <%= ENV.fetch("DATABASE_TEST_NAME", "momtools_hub_test") %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
